#server:
#  port: 8883
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  application:
#    name: service-consumer
#  cloud:
#    config:
#      enabled: true
#      discovery:
#        service-id: config-server
#      profile: test
#      label: master
#      name: application-test
#    bus:
#      enabled: true
#      trace:
#        enabled: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://dush:8881/eureka/
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
